input {
  beats {
    port => 5044
  }

  tcp {
    port => 5000
    codec => json_lines
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user => "${LOGSTASH_WRITER_USER}"
    password => "${LOGSTASH_WRITER_PASSWORD}"
    index => "tracehunt-raw-%{+YYYY.MM.dd}"
    manage_template => false
    ilm_enabled => false
  }
}
